### ISSUE TITLE
Rserve: Socket locked?

### ISSUE THREAD

**Issue by rapofran** [clbustos/Rserve-Ruby-client#22]
Hi @clbustos, first thanks for this ruby gem!

Now I'm facing a weird problem, I'm newbie in Rserve, but sometimes (randomly) I get processes locked and the logs show me this:

``app_folder/shared/bundle/ruby/2.1.0/gems/rserve-client-0.3.1/lib/rserve/talk.rb:91:in `recv'
app_folder/shared/bundle/ruby/2.1.0/gems/rserve-client-0.3.1/lib/rserve/talk.rb:91:in `request'
app_folder/shared/bundle/ruby/2.1.0/gems/rserve-client-0.3.1/lib/rserve/connection.rb:199:in `eval'``

other times show me this:

``app_folder/shared/bundle/ruby/2.1.0/gems/rserve-client-0.3.1/lib/rserve/talk.rb:72:in `recv'
app_folder/shared/bundle/ruby/2.1.0/gems/rserve-client-0.3.1/lib/rserve/talk.rb:72:in `request'
app_folder/shared/bundle/ruby/2.1.0/gems/rserve-client-0.3.1/lib/rserve/connection.rb:199:in `eval'``

Both in the `recv` call of the socket. I'm sure this is NOT an issue with Rserve-Ruby-client, but maybe you could give some useful information about this. Or may be you've already faced this problem before.

Thanks

**Comment by rapofran** [comment]
Hi, I've added a branch with a first version of sockets with timeouts.

https://github.com/rapofran/Rserve-Ruby-client/tree/sockets-with-timeouts

I'm planing to improve the tests and make a pull request

**Comment by clbustos** [comment]
Oh, great!!!
A question: where do you came from?

On Mon, Mar 16, 2015 at 9:48 AM, Juan Francisco Raposeiras <
notifications@github.com> wrote:

> Hi, I've added a branch with a first version of sockets with timeouts.
>
> https://github.com/rapofran/Rserve-Ruby-client/tree/sockets-with-timeouts
>
> I'm planing to improve the tests and make a pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clbustos/Rserve-Ruby-client/issues/22#issuecomment-81636090>
> .
>



-- 
Claudio Bustos
Psicólogo
clbustos@gmail.com

**Comment by rapofran** [comment]
@clbustos could you help me to fix the tests in rserve_talk_spec.rb? (there are 3 failures). The socket timeout's tests are working ok by now.

**Comment by dcassanego** [comment]
I know this is a very old thread, but I am facing this same issue...

@rapofran - have you successfully used your fork from 2015?  I'm interested in whether your approach can help address the timeouts i'm seeing when using RServe (especially when I am making a lot of calls against RServe over a long period of time).

Thanks to you both for this library!

**Comment by rapofran** [comment]
hi @dcassanego unfortunately I'm not using this gem (and project) anymore. But in 2015 it helped me the timeouts and I remember it worked.

Did you give it a try? Are you having problems?
